title: PLSE Conference Deadlines # (Maintained by @zhangysh1995)

description: Countdowns to top PL and SE conference deadlines
author: Tyson Loveless (forked from @abhshkdz)
domain: ""
baseurl: "https://tlove004.github.io/plse-deadlines"

twitter_username: yeezy123
twitter_hashtag: plresearch
github_username: tlove004
github_repo: plse-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
